import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Menu } from '@/components/menu'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LE | Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-zinc-950 text-zinc-100 antialiased">
      <Toaster richColors />
      <body className={inter.className}>
        <div>
          <Menu />
          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  )
}
